// REGISTER
const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
// LOGIN
const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
// SHOW PRODUCT PAGE
const SHOW_PRODUCT_PAGE = "SHOW_PRODUCY_PAGE";
const HIDE_PRODUCT_PAGE = "HIDE_PRODUCY_PAGE";
export {
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  SHOW_PRODUCT_PAGE,
  HIDE_PRODUCT_PAGE,
};
